#################################
# Stage 1 - Builder
#################################

FROM python:3.11-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --user -r requirements.txt

COPY app.py .

#################################
# Stage 2 - Distroless
#################################

FROM gcr.io/distroless/python3

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY --from=builder /app /app

ENV PATH=/root/.local/bin:$PATH

CMD ["app.py"]
